'use strict'
const router = require('koa-router')
const config = require('config')
const mock = require('./controllers/mock')
const project = require('./controllers/project')
const intface = require('./controllers/interface')
const routerPrefix = config.get('routerPrefix')
const util = require('./util/index')

exports.kyeeUI = router({ prefix: routerPrefix.kyeeUI}).all('*',util.view)
exports.mockView = router({ prefix: routerPrefix.kyeeMock}).all('*',util.view)
exports.mock = router({ prefix: routerPrefix.mock })
    .all('*' ,mock.getMock)
exports.api = router({ prefix: routerPrefix.api })
    .all('/project',project.list)
    .all('/project/delete',project.removeById)
    .all('/interface/list',intface.list)
    .all('/interface/delete',intface.removeById)
    .post('/project/create',project.create)
    .post('/project/update',project.updateById)
	.post('/project/audit',project.auditWAP)
	.post('/project/findWAP',project.WAPList)
	.post('/project/deleteWAP',project.backWAP)
    .post('/interface/create',intface.create)
    .post('/interface/update',intface.updateById)